#!/usr/bin/env bash
set -e # Abort on errors

usage() {
  cat <<EOF
Usage: $(basename $0) deb|rpm

  Create a Pyskool Debian or RPM package.
EOF
  exit 1
}

PKGTYPE=$1
[ "$PKGTYPE" = "deb" ] || [ "$PKGTYPE" = "rpm" ] || usage

if [ -z "$PYSKOOL_HOME" ]; then
  echo "Error: PYSKOOL_HOME not defined."
  exit 1
fi
if [ ! -d "$PYSKOOL_HOME" ]; then
  echo "Error: directory not found: $PYSKOOL_HOME"
  exit 1
fi

cd $PYSKOOL_HOME
VERSION=$(./pyskool.py --version | cut -f1 -d' ')
PYSKOOL_TAR=pyskool-pkg-$VERSION.tar.xz
if [ -f "dist/$PYSKOOL_TAR" ]; then
  echo "Using existing $PYSKOOL_TAR"
else
  echo "Building $PYSKOOL_TAR"
  utils/mkpstarball -q -t -p
fi

if [ "$PKGTYPE" = "deb" ]; then
  cd dist
  tar xf $PYSKOOL_TAR
  cd pyskool-$VERSION
  cp -a $PYSKOOL_HOME/debian .
  debuild -b -us -uc
  rm -rf ../pyskool_$VERSION*.build ../pyskool_$VERSION*.changes
  cd $PYSKOOL_HOME
  echo "Created $(ls $PYSKOOL_HOME/dist/pyskool_$VERSION-*.deb)"
elif [ "$PKGTYPE" = "rpm" ]; then
  cp -p dist/$PYSKOOL_TAR ~/rpmbuild/SOURCES/pyskool-$VERSION.tar.xz
  rm -f ~/rpmbuild/RPMS/noarch/pyskool-$VERSION-*.rpm
  rpmbuild -bb rpm/pyskool.spec
  mv ~/rpmbuild/RPMS/noarch/pyskool-$VERSION-*.rpm dist
  echo "Created $(ls $PYSKOOL_HOME/dist/pyskool-$VERSION-*.rpm)"
fi
