#!/usr/bin/env bash
set -e # Abort on errors

PSTMPDIR=$HOME/tmp
COMMANDS=$(echo {skool_daze{,_take_too},back_to_skool{,_daze},ezad_looks}.py)

###############################################################################
# Check required environment variables
###############################################################################
_require_pyskool() {
  if [ -z "$PYSKOOL_HOME" ]; then
    echo "Error: PYSKOOL_HOME not defined."
    exit 1
  fi
  if [ ! -d "$PYSKOOL_HOME" ]; then
    echo "Error: directory not found: $PYSKOOL_HOME"
    exit 1
  fi
  TOOLS=$PYSKOOL_HOME/utils
  VERSION=$($PYSKOOL_HOME/pyskool.py --version 2>&1)
  TARBALL=$PYSKOOL_HOME/dist/pyskool-$VERSION.tar.xz
}

_require_pyskool_archive() {
  if [ -z "$PYSKOOL_ARCHIVE" ]; then
    echo 'PYSKOOL_ARCHIVE is not set; aborting'
    exit 1
  fi
  if [ ! -d "$PYSKOOL_ARCHIVE" ]; then
    echo "PYSKOOL_ARCHIVE=$PYSKOOL_ARCHIVE: directory not found"
    exit 1
  fi
}

_require_skoolkit() {
  if [ -z "$SKOOLKIT_HOME" ]; then
    echo "Error: SKOOLKIT_HOME not defined."
    exit 1
  fi
  if [ ! -d "$SKOOLKIT_HOME" ]; then
    echo "Error: directory not found: $SKOOLKIT_HOME"
    exit 1
  fi
}

###############################################################################
# Utility functions
###############################################################################
_exec() {
  message=$1
  command=$2
  logfile=$3

  echo -n "${message}: "
  if ! $command &> $logfile; then
    echo "FAILED (see $logfile)"
    return 1
  fi
  echo "OK"
}

_cd_tmpdir() {
  mkdir -p $PSTMPDIR
  cd $(mktemp -d --tmpdir=$PSTMPDIR)
}

_create_venv() {
  venvdir=${1:-venv}

  _exec "Creating virtual environment" "virtualenv --system-site-packages $venvdir" $(pwd)/venv.log
}

_build_tarball() {
  echo -n "Building $(basename $TARBALL): "
  $TOOLS/mkpstarball -q -t
  echo "OK"
}

_check_commands() {
  path=$1
  logdir=$2

  for cmdname in $COMMANDS; do
    echo -n "Running '$cmdname --help': "
    cmd=$path/$cmdname
    if [[ ! -f $cmd ]]; then
      echo "FAILED ($cmd not found)"
      return 1
    fi
    logfile=$logdir/$(basename $cmdname .py)-help.log
    $cmd --help &> $logfile || :
    firstword=$(head -n 1 $logfile | cut -f1 -d' ')
    if [[ "$firstword" != "usage:" ]]; then
      echo "FAILED (see $logfile)"
      return 1
    fi
    echo "OK"
  done
}

_check_man_pages() {
  echo -n "Checking man pages: "
  for cmdname in $COMMANDS; do
    manpage=/usr/share/man/man6/$cmdname.6.gz
    if [[ ! -f $manpage ]]; then
      echo "FAILED ($manpage not found)"
      return 1
    fi
  done
  echo "OK"
}

_check_files() {
  filetype=$1
  expdir=$2
  logdir=$3
  shift 3
  expfiles=$*

  echo -n "Checking $filetype: "
  if [[ ! -d $expdir ]]; then
    echo "FAILED ($expdir does not exist)"
    return 1
  fi
  rcount=0
  for f in $expfiles; do
    resource=$expdir/$f
    if [[ ! -f $resource ]]; then
      echo "FAILED ($f not found in $expdir)"
      return 1
    fi
    let rcount+=1
  done
  rlist=$logdir/$filetype.txt
  ls -1 $expdir > $rlist
  numresources=$(cat $rlist | grep -v examples | wc -l)
  if [[ $numresources -ne $rcount ]]; then
    echo "FAILED (unexpected files found; see $rlist)"
    return 1
  fi
  echo "OK"
}

_check_data() {
  rootdir=$1
  logdir=$2

  _check_files data $rootdir $logdir {images,pyskool}.ini
}

_check_setup() {
  path=$1
  logdir=$2

  for cmdname in $COMMANDS; do
    logfile=$logdir/$(basename $cmdname .py)-setup.log
    _exec "Running '$cmdname --setup'" "$path/$cmdname --setup" $logfile
  done
}

_run_commands() {
  path=$1
  logdir=$2

  for cmdname in $COMMANDS; do
    logfile=$logdir/$(basename $cmdname .py).log
    _exec "Running $cmdname" "$path/$cmdname" $logfile
  done
}

###############################################################################
# Compare images with those in the previous version
###############################################################################
compare_images() {
  _require_pyskool
  _require_pyskool_archive
  _require_skoolkit

  cd $PYSKOOL_HOME
  prev_version=$(git tag | tail -n 1 | cut -c2-)
  _build_tarball
  _cd_tmpdir
  tar xf $PYSKOOL_ARCHIVE/pyskool-$prev_version.tar.xz
  tar xf $TARBALL
  cmd="$TOOLS/compare-images pyskool-$prev_version pyskool-$VERSION"
  logfile=$(pwd)/images.txt
  _exec "Comparing images with those in version $prev_version" "$cmd" $logfile
  [[ -s $logfile ]] && echo "Differences found (see $logfile)" || echo "No differences found"
}

###############################################################################
# Verify that 'setup.py install' works
###############################################################################
_install_pyskool() {
  method=$1

  tar xf $TARBALL -C $topdir
  mv $topdir/pyskool-$VERSION{,-release}
  cd $topdir/pyskool-$VERSION-release

  if [[ "$method" = "2" ]]; then
    _exec "Building source distribution" "./setup.py sdist" $topdir/sdist.log
    tar xf dist/pyskool-$VERSION.tar.gz -C $topdir
    cd $topdir/pyskool-$VERSION
  fi

  _exec "Installing Pyskool" "$venv/bin/python setup.py install" $topdir/install.log
}

verify_setup() {
  method=$1

  _require_pyskool

  _build_tarball
  _cd_tmpdir
  topdir=$(pwd)
  venv=$topdir/venv
  _create_venv $venv
  _install_pyskool $method
  _check_commands $venv/bin $topdir
  packagedir=$($venv/bin/skool_daze.py --package-dir)
  _check_data $packagedir/data $topdir

  [[ -d $HOME/.pyskool ]] && mv $HOME/.pyskool{,-backup}

  _check_setup $venv/bin $topdir
  _run_commands $venv/bin $topdir

  rm -rf $HOME/.pyskool
  [[ -d $HOME/.pyskool-backup ]] && mv $HOME/.pyskool{-backup,}
}

###############################################################################
# Build, install, verify and uninstall a DEB package
###############################################################################
build_deb() {
  _require_pyskool

  debname=pyskool_$VERSION-1_all.deb
  deb=$PYSKOOL_HOME/dist/$debname
  logdir=$PYSKOOL_HOME/dist
  mkdir -p $logdir

  sudo dpkg -r pyskool &> /dev/null

  _exec "Building $debname" "make -C $PYSKOOL_HOME deb" $logdir/debuild.log
  _exec "Installing $debname" "sudo dpkg -i $deb" $logdir/dpkg-i.log
  _check_commands /usr/games $logdir
  _check_man_pages
  _check_data $(/usr/games/skool_daze.py --package-dir)/data $logdir

  [[ -d $HOME/.pyskool ]] && mv $HOME/.pyskool{,-backup}
  _run_commands /usr/games $logdir
  rm -rf $HOME/.pyskool
  [[ -d $HOME/.pyskool-backup ]] && mv $HOME/.pyskool{-backup,}

  _exec "Uninstalling pyskool" "sudo dpkg -r pyskool" $logdir/dpkg-r.log

  echo "Now upload $deb to pyskool.ca"
}

###############################################################################
# Build, install, verify and uninstall an RPM package
###############################################################################
build_rpm() {
  _require_pyskool

  rpmname=pyskool-$VERSION-1.noarch.rpm
  rpm=$PYSKOOL_HOME/dist/$rpmname
  logdir=$PYSKOOL_HOME/dist
  mkdir -p $logdir

  sudo rpm -e pyskool &> /dev/null || true

  _exec "Building $rpmname" "make -C $PYSKOOL_HOME rpm" $logdir/rpmbuild.log
  _exec "Installing $rpmname" "sudo rpm -i $rpm" $logdir/rpm-i.log
  _check_commands /usr/bin $logdir
  _check_man_pages
  _check_data $(/usr/bin/skool_daze.py --package-dir)/data $logdir

  [[ -d $HOME/.pyskool ]] && mv $HOME/.pyskool{,-backup}
  _run_commands /usr/bin $logdir
  rm -rf $HOME/.pyskool
  [[ -d $HOME/.pyskool-backup ]] && mv $HOME/.pyskool{-backup,}

  _exec "Uninstalling pyskool" "sudo rpm -e pyskool" $logdir/rpm-e.log

  echo "Now upload $rpm to pyskool.ca"
}

###############################################################################
# Prepare documentation on the gh-pages branch
###############################################################################
prepare_gh_pages() {
  _require_pyskool

  _cd_tmpdir
  logfile=$(pwd)/sphinx.log
  echo -n "Cloning pyskool repository: "
  git clone -q https://github.com/skoolkid/pyskool
  echo "OK"
  cd pyskool
  sed -i 's/^\(SPHINXOPTS.*=\)$/\1 -D html_theme=sphinxdoc/' sphinx/Makefile
  _exec "Building documentation" "make -C sphinx html" $logfile
  git checkout -- sphinx/Makefile
  rm -rf sphinx/build/html/{.buildinfo,objects.inv}
  git checkout -q gh-pages
  rsync -a sphinx/build/html/ .
  rm -rf pyskool sphinx
  echo
  git status -bs
  cat <<EOM

Now:
  \$ cd $(pwd)
  # Remove any pages that are no longer used
  # Add any new pages or files
  \$ git commit -am "Update Pyskool documentation to $VERSION"
  \$ git push origin gh-pages
EOM
}

###############################################################################
# Build a source package for uploading to PyPI
###############################################################################
build_sdist() {
  _require_pyskool

  [[ -f $TARBALL ]] && echo "Found $TARBALL" || _build_tarball
  _cd_tmpdir
  logfile=$(pwd)/sdist.log
  tar xf $TARBALL
  cd pyskool-$VERSION
  _exec "Building source package" "./setup.py sdist" $logfile
  sdist=pyskool-$VERSION.tar.gz
  mv dist/$sdist $PYSKOOL_HOME/dist
  echo "Now upload $PYSKOOL_HOME/dist/$sdist to PyPI"
}

###############################################################################
# Verify that Pyskool can be installed from PyPI
###############################################################################
check_pypi() {
  _cd_tmpdir
  _create_venv
  _exec "Installing Pyskool from PyPI" "venv/bin/pip install pyskool" $(pwd)/install.log

  [[ -d $HOME/.pyskool ]] && mv $HOME/.pyskool{,-backup}
  _check_setup venv/bin $(pwd)
  _run_commands venv/bin $(pwd)
  rm -rf $HOME/.pyskool
  [[ -d $HOME/.pyskool-backup ]] && mv $HOME/.pyskool{-backup,}
}

###############################################################################
# Build a documentation zip archive for PyPI
###############################################################################
build_doczip() {
  _require_pyskool

  mkdir -p $PYSKOOL_HOME/dist
  zipfile=$PYSKOOL_HOME/dist/pyskool-$VERSION-docs.zip

  _cd_tmpdir
  echo -n "Cloning local git repository: "
  git clone -ql $PYSKOOL_HOME
  echo "OK"
  logfile=$(pwd)/sphinx.log
  cd pyskool/sphinx
  sed -i 's/^\(SPHINXOPTS.*=\)$/\1 -D html_theme=nature/' Makefile
  _exec "Building documentation" "make html" $logfile
  cd build/html
  rm -f .buildinfo objects.inv $zipfile
  echo -n "Building zip archive: "
  zip -9qr $zipfile .
  echo "OK"
  echo "Now upload $zipfile to PyPI"
}

###############################################################################
# Print usage information
###############################################################################
usage() {
  cat >&2 <<EOM
Usage: $(basename $0) COMMAND [COMMAND...]

Pyskool testing and release tool.

Pre-release commands:
  cmpimg - compare images with those in the previous version
  setup1 - verify that 'setup.py install' works from a release tarball
  setup2 - verify that 'setup.py install' works from an sdist tarball

Post-release commands:
  debpkg - build, install, verify and uninstall a DEB package
  rpmpkg - build, install, verify and uninstall an RPM package
  ghdocs - prepare documentation on the gh-pages branch
  bsdist - build a source package for uploading to PyPI
  ifpypi - verify that Pyskool can be installed from PyPI
  doczip - build a documentation zip archive for PyPI
EOM
}

###############################################################################
# Parse command line
###############################################################################
[[ -z "$1" ]] && usage
numcommands=$#

while [[ -n "$1" ]]; do
  [[ $numcommands -ge 2 ]] && echo "*** Running command '$1' ***"
  case "$1" in
    cmpimg) compare_images ;;
    setup1) verify_setup 1 ;;
    setup2) verify_setup 2 ;;
    debpkg) build_deb ;;
    rpmpkg) build_rpm ;;
    ghdocs) prepare_gh_pages ;;
    bsdist) build_sdist ;;
    ifpypi) check_pypi ;;
    doczip) build_doczip ;;
         *) echo "*** Unknown command '$1' ***"; usage ;;
  esac
  shift
done
